#!/usr/bin/env node
/**
 * chdb-node × @clickhouse/client cross-suite parity runner.
 *
 * Clones @clickhouse/client at a configured ref, builds it, injects
 * `tests/clickhouse-js/inject_setup.ts` as an additional vitest setup
 * file so every `createClient` call is wrapped with
 * `createChdbConnection`, then runs the integration suite filtered by
 * `tests/clickhouse-js/skip_list.json`.
 *
 * Sync policy (encoded in skip_list.json's `syncedAgainst` block):
 *
 *   stage of the upstream injection PR     →  ref this runner uses
 *   ----------------------------------------+-----------------------
 *   open on the personal fork (today)       →  ShawnChen-Sirius/clickhouse-js
 *                                              feat/pluggable-connection
 *   merged to ClickHouse/clickhouse-js     →  ClickHouse/clickhouse-js main
 *   released                                →  the latest released tag
 *
 * Override at runtime:
 *
 *   CHDB_CLICKHOUSE_JS_REPO=https://github.com/.../clickhouse-js.git
 *   CHDB_CLICKHOUSE_JS_REF=feat/pluggable-connection
 *
 * Usage:
 *
 *   node tests/clickhouse-js/runner.mjs              — run the whole suite
 *   node tests/clickhouse-js/runner.mjs --refresh    — re-clone (no cache)
 */

import { spawnSync } from "node:child_process";
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync, cpSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const HERE = dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = resolve(HERE, "../..");

const SKIP = JSON.parse(readFileSync(join(HERE, "skip_list.json"), "utf8"));
const synced = SKIP.syncedAgainst || {};

const REPO = process.env.CHDB_CLICKHOUSE_JS_REPO
  || (synced.ref?.startsWith("ShawnChen-Sirius/")
        ? "https://github.com/ShawnChen-Sirius/clickhouse-js.git"
        : "https://github.com/ClickHouse/clickhouse-js.git");
const REF = process.env.CHDB_CLICKHOUSE_JS_REF
  || synced.ref?.split(" ").pop()
  || "main";

const WORK_DIR = process.env.CHDB_RUNNER_WORK_DIR
  || join(REPO_ROOT, ".chdb-runner", "clickhouse-js");
const REFRESH = process.argv.includes("--refresh");

function sh(cmd, args, opts = {}) {
  console.log(`[runner] $ ${cmd} ${args.join(" ")}${opts.cwd ? `   (in ${opts.cwd})` : ""}`);
  const r = spawnSync(cmd, args, { stdio: "inherit", ...opts });
  if (r.status !== 0) {
    throw new Error(`${cmd} ${args.join(" ")} → exit ${r.status}`);
  }
}

function clone() {
  if (REFRESH && existsSync(WORK_DIR)) {
    rmSync(WORK_DIR, { recursive: true, force: true });
  }
  if (existsSync(WORK_DIR)) {
    sh("git", ["-C", WORK_DIR, "fetch", "origin"]);
    sh("git", ["-C", WORK_DIR, "checkout", REF]);
    sh("git", ["-C", WORK_DIR, "pull", "--ff-only", "origin", REF]);
    return;
  }
  mkdirSync(dirname(WORK_DIR), { recursive: true });
  sh("git", ["clone", "--depth", "50", "--branch", REF, REPO, WORK_DIR]);
}

function installAndBuild() {
  sh("npm", ["install"], { cwd: WORK_DIR });
  sh("npm", ["--workspaces", "run", "build"], { cwd: WORK_DIR });
  // Link this chdb-node checkout as the `chdb` dependency so the injection
  // setup can `import { createChdbConnection } from 'chdb/connection'`.
  sh("npm", ["install", REPO_ROOT, "--save-dev"], { cwd: WORK_DIR });
}

function injectSetup() {
  // Compile our inject_setup.ts into the upstream tree as a .js file (no
  // ts-node bootstrapping needed). Simpler than configuring vitest to pick
  // up a TS file from outside the project root.
  const SETUP_JS = `// Auto-generated by chdb-node/tests/clickhouse-js/runner.mjs
const { createClient } = require("@clickhouse/client");
const { createChdbConnection } = require("chdb/connection");
globalThis.environmentSpecificCreateClient = (config) => {
  const connection = createChdbConnection({ path: ":memory:" });
  return createClient({ ...(config || {}), connection });
};
console.log("[chdb-runner] createClient wrapped with ChdbConnection");
`;
  const target = join(WORK_DIR, "vitest.chdb.setup.cjs");
  writeFileSync(target, SETUP_JS);
  return target;
}

function buildSkipPattern() {
  const files = (SKIP.skipFiles || []).map((entry) =>
    typeof entry === "string" ? entry : entry.file);
  return files;
}

/**
 * For each `skipTests` entry, patch the relevant test file in place so the
 * matching `it("<name>"` becomes `it.skip("<name>"` (and same for `test(`).
 * Returns a list of `{ file, original }` snapshots so the caller can
 * restore the originals after vitest finishes. vitest 2.x has no native
 * test-id-level skip via CLI, so in-place patching is the simplest
 * cross-file mechanism.
 */
function applyPerTestSkips() {
  const entries = SKIP.skipTests || [];
  if (entries.length === 0) return [];
  const patches = [];
  // Group entries by file so we make one read/write per file.
  const byFile = new Map();
  for (const e of entries) {
    if (!byFile.has(e.file)) byFile.set(e.file, []);
    byFile.get(e.file).push(e);
  }
  for (const [relFile, list] of byFile) {
    const abs = join(WORK_DIR, relFile);
    if (!existsSync(abs)) {
      console.warn(`[runner] skipTests file not found, ignoring: ${relFile}`);
      continue;
    }
    const original = readFileSync(abs, "utf8");
    let patched = original;
    let applied = 0;
    for (const e of list) {
      // The vitest test node-id is `<file> > <describe...> > <it-name>`.
      // We only need the LAST segment (the `it` name) to locate the
      // `it("<name>"` call in the source.
      const itName = e.test.split(" > ").pop();
      // Escape regex metacharacters in the it name.
      const escaped = itName
        .replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
      // Match `it(` or `test(` followed by the string literal of itName.
      const re = new RegExp(
        String.raw`\b(it|test)\(\s*(['"\`])${escaped}\2`,
        "g",
      );
      const next = patched.replace(re, "$1.skip($2" + itName + "$2");
      if (next !== patched) {
        applied += 1;
        patched = next;
      } else {
        console.warn(
          `[runner] skipTests: pattern not found in ${relFile}: ${itName}`,
        );
      }
    }
    if (patched !== original) {
      writeFileSync(abs, patched);
      patches.push({ file: abs, original });
      console.log(
        `[runner] applied ${applied} per-test skip(s) to ${relFile}`,
      );
    }
  }
  return patches;
}

function restorePerTestSkips(patches) {
  for (const { file, original } of patches) {
    try {
      writeFileSync(file, original);
    } catch (e) {
      console.warn(`[runner] failed to restore ${file}: ${e.message}`);
    }
  }
}

function runVitest() {
  injectSetup();
  const excludes = buildSkipPattern();
  const patches = applyPerTestSkips();
  try {
    const args = [
      "run",
      "test:node:integration",
      "--",
      "--config",
      "vitest.node.config.ts",
    ];
    for (const f of excludes) args.push("--exclude", f);
    const env = {
      ...process.env,
      TZ: "UTC",
      // Tell upstream's setup.ts (if it cooperates) that the backend is chdb.
      CH_TEST_BACKEND: "chdb",
    };
    sh("npm", args, { cwd: WORK_DIR, env });
  } finally {
    restorePerTestSkips(patches);
  }
}

console.log(`[runner] @clickhouse/client repo: ${REPO}`);
console.log(`[runner] ref:                       ${REF}`);
console.log(`[runner] work dir:                  ${WORK_DIR}`);
console.log(`[runner] skip_list entries:         ${(SKIP.skipFiles || []).length} files`);
console.log();

clone();
installAndBuild();
runVitest();
