/**
 * Emit a TypeScript module declaring a database schema as ClickHouse type
 * string literals. The emitted shape is exactly what `Database<DB>` consumes,
 * so `chdb.database<Db>().selectFrom('events')` infers the row at .execute().
 *
 * The output is deterministic (alphabetized tables, columns in DESCRIBE order)
 * and self-contained — no runtime imports — so a generated file diffs cleanly
 * and a build that pins it is reproducible.
 */

import type { IntrospectedDatabase } from './introspect'
import { ChdbCompileError } from '../../errors'

export interface EmitOptions {
  /** Name of the emitted interface. Defaults to `Database`. */
  interfaceName?: string
  /** Optional banner line(s) — e.g. a source tag, commit, command line. */
  banner?: string
}

const IDENT_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/

function quoteKey(name: string): string {
  return IDENT_RE.test(name) ? name : JSON.stringify(name)
}

/** Single-quote a ClickHouse type literal, escaping only the inner single quotes. */
function quoteType(ch: string): string {
  return `'${ch.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}

/** Render a `{ table → column → CH-type }` map as a TypeScript module string. */
export function emitDatabase(db: IntrospectedDatabase, opts: EmitOptions = {}): string {
  const name = opts.interfaceName ?? 'Database'
  // The interface name comes from the user-supplied `--name` flag and is
  // interpolated into the declaration verbatim, so reject anything that isn't a
  // valid TS identifier rather than emitting a module that fails to compile.
  if (!IDENT_RE.test(name)) {
    throw new ChdbCompileError(`gen-types: interface name ${JSON.stringify(name)} is not a valid TypeScript identifier`)
  }
  const tables = Object.keys(db).sort()
  const lines: string[] = []
  lines.push('// Generated by chdb gen-types. Do not edit by hand.')
  if (opts.banner !== undefined && opts.banner !== '') {
    for (const b of opts.banner.split('\n')) lines.push(`// ${b}`)
  }
  lines.push('')
  lines.push(`export interface ${name} {`)
  for (const table of tables) {
    const cols = db[table] ?? {}
    const colNames = Object.keys(cols)
    if (colNames.length === 0) {
      lines.push(`  ${quoteKey(table)}: Record<string, never>`)
      continue
    }
    lines.push(`  ${quoteKey(table)}: {`)
    for (const col of colNames) {
      lines.push(`    ${quoteKey(col)}: ${quoteType(cols[col]!)}`)
    }
    lines.push('  }')
  }
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}
