import { describe, it, expect, beforeAll, afterAll, beforeEach } from 'vitest'
import { mkdtempSync, writeFileSync, readFileSync, rmSync } from 'fs'
import { tmpdir } from 'os'
import { join } from 'path'
import { spawnSync } from 'child_process'
import {
  introspectTable,
  introspectDatabase,
  emitDatabase,
  session,
  connect,
  query,
} from '../../../index.js'
import { parseArgs, planSources, main } from '../../../src/layer3/codegen/cli'

// gen-types: introspect a source (file / table / federated url) and emit a
// TypeScript Database interface ready to feed into `database<Db>()`. The
// programmatic API and the CLI share the same code, so the tests exercise
// both: a unit pass over the emitter / arg parser, a real introspect against
// a local CSV and a live Postgres if reachable, and a CLI smoke spawn.

describe('emitDatabase — deterministic, identifier-safe rendering', () => {
  it('sorts tables, single-quotes the CH type, and quotes non-ident keys', () => {
    expect(
      emitDatabase(
        {
          events: { id: 'UInt64', country: 'String' },
          'weird-name': { 'col with space': "DateTime('UTC')", quoteCol: "name's escaped" },
        },
        { interfaceName: 'Db', banner: 'fixture' },
      ),
    ).toBe(
      [
        '// Generated by chdb gen-types. Do not edit by hand.',
        '// fixture',
        '',
        'export interface Db {',
        '  events: {',
        "    id: 'UInt64'",
        "    country: 'String'",
        '  }',
        '  "weird-name": {',
        '    "col with space": \'DateTime(\\\'UTC\\\')\'',
        "    quoteCol: 'name\\'s escaped'",
        '  }',
        '}',
        '',
      ].join('\n'),
    )
  })

  it('renders an empty table as Record<string, never>', () => {
    expect(emitDatabase({ empty: {} })).toContain('empty: Record<string, never>')
  })
})

describe('CLI argv parsing and source planning', () => {
  it('accepts both `--key value` and `--key=value`', () => {
    const a = parseArgs(['--from-file', '/x.csv', '--name=Db', '--out=/tmp/o.d.ts'])
    expect(a.fromFile).toBe('/x.csv')
    expect(a.name).toBe('Db')
    expect(a.out).toBe('/tmp/o.d.ts')
  })

  it('rejects unknown options and missing source / values', () => {
    expect(() => parseArgs(['--zoinks', 'x'])).toThrow(/Unknown option/)
    expect(() => parseArgs(['--name'])).toThrow(/Missing value/)
    expect(() => planSources(parseArgs([]))).toThrow(/Pick one source mode/)
    expect(() =>
      planSources(parseArgs(['--from-file', '/x', '--from-table', 't'])),
    ).toThrow(/exactly one source mode/)
    expect(() => planSources(parseArgs(['--from-url', 'postgres://h/d']))).toThrow(/at least one --table/)
  })

  it('builds the right source plan for each mode', () => {
    expect(planSources(parseArgs(['--from-file', '/x.csv', '--format', 'CSV']))).toEqual({
      mode: 'introspect',
      sources: { file: { kind: 'file', path: '/x.csv', format: 'CSV', structure: undefined } },
    })
    expect(planSources(parseArgs(['--from-table', 'events']))).toEqual({
      mode: 'introspect',
      sources: { events: { kind: 'table', name: 'events' } },
    })
    expect(
      planSources(parseArgs(['--from-url', 'postgres://h/d', '--table', 'users', '--table', 'orders'])),
    ).toEqual({
      mode: 'introspect',
      sources: {
        users: { kind: 'url', config: { url: 'postgres://h/d', username: undefined, password: undefined, database: undefined }, table: 'users' },
        orders: { kind: 'url', config: { url: 'postgres://h/d', username: undefined, password: undefined, database: undefined }, table: 'orders' },
      },
    })
  })
})

describe('introspectTable / Database — real local file', () => {
  const dir = mkdtempSync(join(tmpdir(), 'l3-codegen-'))
  const csv = join(dir, 'events.csv')
  afterAll(() => rmSync(dir, { recursive: true, force: true }))

  beforeEach(() => {
    writeFileSync(csv, 'id,country,score\n1,US,9.5\n2,FR,3.0\n')
  })

  it('reads a column → CH-type map from a CSV with a header', async () => {
    const schema = await introspectTable({ kind: 'file', path: csv, format: 'CSVWithNames' })
    expect(Object.keys(schema)).toEqual(['id', 'country', 'score'])
    expect(schema.id).toBe('Nullable(Int64)')
    expect(schema.country).toBe('Nullable(String)')
    expect(schema.score).toBe('Nullable(Float64)')
  })

  it('introspectDatabase keys by the label the caller picked', async () => {
    const db = await introspectDatabase({ stuff: { kind: 'file', path: csv, format: 'CSVWithNames' } })
    expect(Object.keys(db)).toEqual(['stuff'])
    expect(Object.keys(db.stuff!)).toEqual(['id', 'country', 'score'])
  })

  it('round-trips: file → schema → emitted module', async () => {
    const db = await introspectDatabase({ events: { kind: 'file', path: csv, format: 'CSVWithNames' } })
    const ts = emitDatabase(db, { interfaceName: 'Db' })
    expect(ts).toMatch(/export interface Db \{[\s\S]*events: \{[\s\S]*id: 'Nullable\(Int64\)'[\s\S]*\}/)
  })
})

describe('introspectTable — a local table on a Session', () => {
  let db: ReturnType<typeof session>
  beforeEach(() => {
    db = session()
  })

  it('reads a CREATE TABLE schema back as CH type strings', async () => {
    await db.session!.queryAsync(
      "CREATE TABLE t (id UInt64, name String, ts DateTime('UTC'), cnt Nullable(UInt32)) ENGINE = Memory",
    )
    const schema = await introspectTable({ kind: 'table', name: 't' }, { session: db.session })
    expect(schema).toEqual({
      id: 'UInt64',
      name: 'String',
      ts: "DateTime('UTC')",
      cnt: 'Nullable(UInt32)',
    })
    db.close()
  })
})

describe('CLI — end-to-end', () => {
  const dir = mkdtempSync(join(tmpdir(), 'l3-cli-'))
  const csv = join(dir, 'events.csv')
  const outFile = join(dir, 'schema.d.ts')
  beforeAll(() => writeFileSync(csv, 'id,country\n1,US\n'))
  afterAll(() => rmSync(dir, { recursive: true, force: true }))

  it('writes to --out and includes the banner without the cli being mounted on chdb root', async () => {
    let stderr = ''
    const r = await main(['--from-file', csv, '--format', 'CSVWithNames', '--label', 'events', '--name', 'Db', '--out', outFile], {
      stdout: () => undefined,
      stderr: (s) => { stderr += s },
    })
    expect(r.code).toBe(0)
    expect(stderr).toBe('')
    const ts = readFileSync(outFile, 'utf-8')
    expect(ts).toMatch(/export interface Db \{/)
    expect(ts).toMatch(/events: \{/)
    expect(ts).toMatch(new RegExp(`source: file ${csv.replace(/[.+/]/g, '\\$&')}`))
  })

  it('--help exits 0, prints help to stdout, leaves stderr empty', async () => {
    let stdout = ''
    let stderr = ''
    const r = await main(['--help'], { stdout: (s) => { stdout += s }, stderr: (s) => { stderr += s } })
    expect(r.code).toBe(0)
    expect(stdout).toMatch(/Usage: chdb gen-types/)
    expect(stderr).toBe('')
  })

  it('unknown option exits 2 with help on stderr', async () => {
    let stderr = ''
    const r = await main(['--bogus', 'x'], { stdout: () => undefined, stderr: (s) => { stderr += s } })
    expect(r.code).toBe(2)
    expect(stderr).toMatch(/Unknown option/)
    expect(stderr).toMatch(/Usage: chdb gen-types/)
  })

  it('spawns the built bin and produces the same output', () => {
    const r = spawnSync(
      process.execPath,
      ['dist/layer3/codegen/cli.js', '--from-file', csv, '--format', 'CSVWithNames', '--label', 'events'],
      { cwd: process.cwd(), encoding: 'utf-8' },
    )
    expect(r.status).toBe(0)
    expect(r.stdout).toMatch(/export interface Database \{/)
    expect(r.stdout).toMatch(/events: \{[\s\S]*'Nullable\(Int64\)'/)
  })
})

// Live federation against the same Postgres / MySQL the connect() suite uses.
// Skips when no server is reachable so CI without databases stays green.
const PG_URL = process.env.CHDB_TEST_PG_URL ?? 'postgres://postgres:pw@127.0.0.1:55432/app'
function reachable(url: string, table: string): boolean {
  try {
    // The buildSource + query roundtrip in connect.test.ts already proves the
    // probe shape; here we keep it simple and call connect()/describe().
    void connect({ url }).describe(table).then(
      () => undefined,
      () => undefined,
    )
    // Synchronous reach check by running a tiny SELECT through query():
    const sql = `SELECT 1 FROM postgresql('${new URL(url).host}', '${new URL(url).pathname.replace(/^\//, '')}', '${table}', '${new URL(url).username}', '${decodeURIComponent(new URL(url).password)}') LIMIT 1`
    query(sql, 'CSV')
    return true
  } catch {
    return false
  }
}
const PG_OK = reachable(PG_URL, 'users')

describe.skipIf(!PG_OK)('CLI — live Postgres', () => {
  it('introspects a Postgres table and emits a usable Database interface', async () => {
    let stdout = ''
    const r = await main(
      ['--from-url', PG_URL, '--table', 'users', '--name', 'AppDb'],
      { stdout: (s) => { stdout += s }, stderr: () => undefined },
    )
    expect(r.code).toBe(0)
    expect(stdout).toMatch(/export interface AppDb \{/)
    expect(stdout).toMatch(/users: \{[\s\S]*id: 'Nullable\(Int64\)'[\s\S]*country: 'Nullable\(String\)'/)
    // Banner must not leak credentials.
    expect(stdout).not.toMatch(/postgres:pw|password=|:pw@/)
  })
})
