name: chDB-node

on:
  pull_request:
    paths-ignore:
      - '**/.md'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Fetch library
      run: |
          wget https://github.com/chdb-io/chdb/releases/latest/download/linux-x86_64-libchdb.tar.gz
          tar -xzf linux-x86_64-libchdb.tar.gz
          sudo mv libchdb.so /usr/lib/libchdb.so
          sudo ldconfig
    - uses: actions/setup-node@v3
      with:
        node-version: 16
    - run: npm install
    - run: npm test
